export const CATEGORY_ORDER = [
  '开源',
  '科普',
  '获客',
  '纪录片',
  '写实感',
  '真人感',
  '电影感',
  '儿童',
  '动漫',
  '国风',
  '科幻',
  '奇幻',
  '悬疑',
  '商业',
  '复古',
  '图文',
]

export const HOME_CATEGORY_LABELS: Record<string, string> = {
  All: "All",
  开源: "Open Source Project",
  科普: "Knowledge Short Video",
  获客: "Lead Generation Short Video",
  纪录片: "Documentary",
  写实感: "Realistic Feel",
  真人感: "Character Stories",
  电影感: "Movie Commentary",
  儿童: "Emotional Healing",
  动漫: "Animation",
  国风: "Chinese Style",
  科幻: "Sci-Fi",
  奇幻: "Fantasy",
  悬疑: "Mystery",
  商业: "Business Marketing",
  复古: "Retro",
  图文: "Text and Image",
  绘本: "Picture Book",
  故事: "Story", 摄影: "Photography", 胶片: "Film", 剪纸: "Paper Cut",
  手绘: "Hand-Drawn", 赛博: "Cyberpunk", 拼贴: "Collage", 极简: "Minimalist",
  像素: "Pixel Art", 水墨: "Ink Painting",
}
